import type { JSX } from "react";

/**
 * One Apple launch image entry. Dimensions are in CSS (device-independent)
 * pixels; `ratio` is the device pixel ratio. The file name encodes the
 * physical-pixel resolution (cssWidth*ratio x cssHeight*ratio) — it must
 * match the output of scripts/generate-icons.ts.
 */
interface SplashEntry {
  cssWidth: number;
  cssHeight: number;
  ratio: number;
}

/** Common modern iPhone sizes — kept in sync with SPLASH_SIZES in the script. */
const SPLASH_ENTRIES: SplashEntry[] = [
  { cssWidth: 390, cssHeight: 844, ratio: 3 }, // 1170x2532 — iPhone 12/13/14
  { cssWidth: 430, cssHeight: 932, ratio: 3 }, // 1290x2796 — iPhone 14/15 Pro Max
  { cssWidth: 393, cssHeight: 852, ratio: 3 }, // 1179x2556 — iPhone 15/16
  { cssWidth: 428, cssHeight: 926, ratio: 3 }, // 1284x2778 — iPhone 12/13 Pro Max
  { cssWidth: 414, cssHeight: 896, ratio: 2 }, // 828x1792  — iPhone XR / 11
  { cssWidth: 375, cssHeight: 812, ratio: 3 }, // 1125x2436 — iPhone X / XS / 11 Pro
];

/**
 * Emits `<link rel="apple-touch-startup-image">` tags for the iPhone splash
 * screens generated by the icon script. React 19 hoists these into <head>.
 * Render `<AppleSplash />` once in the root layout.
 */
export function AppleSplash(): JSX.Element {
  return (
    <>
      {SPLASH_ENTRIES.map(({ cssWidth, cssHeight, ratio }) => {
        const pxWidth = cssWidth * ratio;
        const pxHeight = cssHeight * ratio;
        const href = `/icons/splash/apple-splash-${pxWidth}x${pxHeight}.png`;
        const media =
          `(device-width: ${cssWidth}px) and (device-height: ${cssHeight}px) ` +
          `and (-webkit-device-pixel-ratio: ${ratio}) and (orientation: portrait)`;
        return (
          <link
            key={href}
            rel="apple-touch-startup-image"
            media={media}
            href={href}
          />
        );
      })}
    </>
  );
}
