/**
 * Apply pending Drizzle migrations to the SQLite database.
 *
 * Run with:  pnpm db:migrate
 *
 * Migrations themselves are generated by drizzle-kit (`pnpm db:generate`),
 * which writes SQL files into ./drizzle. This script only *applies* them.
 */

import { existsSync, mkdirSync } from "node:fs";

import { migrate } from "drizzle-orm/better-sqlite3/migrator";

import { db, sqlite } from "../lib/db/sqlite/client";

const MIGRATIONS_FOLDER = "./drizzle";

function main(): void {
  // The client already ensures the db's parent dir; be explicit about ./data.
  if (!existsSync("./data")) {
    mkdirSync("./data", { recursive: true });
  }

  if (!existsSync(MIGRATIONS_FOLDER)) {
    console.error(
      `No migrations found at ${MIGRATIONS_FOLDER}. Run \`pnpm db:generate\` first.`,
    );
    process.exit(1);
  }

  console.log(`Applying migrations from ${MIGRATIONS_FOLDER} ...`);
  migrate(db, { migrationsFolder: MIGRATIONS_FOLDER });
  console.log("Migrations applied successfully.");

  sqlite.close();
}

main();
